MonsterNames::
	db "קרנשיא@@@@" ; RHYDON
	db "כיסבל@@@@@" ; KANGASKHAN
	db "עקצחלב♂@@@" ; NIDORAN♂
	db "חמשדון@@@@" ; CLEFAIRY
	db "כידרור@@@@" ; SPEAROW
	db "חשמלמל@@@@" ; VOLTORB
	db "מלקץ@@@@@@" ; NIDOKING
	db "אחלאט@@@@@" ; SLOWBRO
	db "פרחריג@@@@" ; IVYSAUR
	db "בצפוטרופוס" ; EXEGGUTOR
	db "עגולשון@@@" ; LICKITUNG
	db "ביצמודות@@" ; EXEGGCUTE
	db "טנפאי@@@@@" ; GRIMER
	db "אשלדאי@@@@" ; GENGAR
	db "עקצחלב♀@@@" ; NIDORAN♀
	db "מלכצת@@@@@" ; NIDOQUEEN
	db "רשרש@@@@@@" ; CUBONE
	db "קרנוזף@@@@" ; RHYHORN
	db "תכוגית@@@@" ; LAPRAS
	db "כלבזק@@@@@" ; ARCANINE
	db "תש@@@@@@@@" ; MEW
	db "לויטורף@@@" ; GYARADOS
	db "קונכך@@@@@" ; SHELLDER
	db "קרשוש@@@@@" ; TENTACOOL
	db "שאד@@@@@@@" ; GASTLY
	db "מגל-שלמה@@" ; SCYTHER
	db "כוכיש@@@@@" ; STARYU
	db "מפציצב@@@@" ; BLASTOISE
	db "צבתך@@@@@@" ; PINSIR
	db "סבכיה@@@@@" ; TANGELA
	db "MISSINGNO." ; MISSINGNO.
	db "MISSINGNO." ; MISSINGNO.
	db "נהמיש@@@@@" ; GROWLITHE
	db "נחשוהם@@@@" ; ONIX
	db "פחדרור@@@@" ; FEAROW
	db "יונדי@@@@@" ; PIDGEY
	db "כיסלאט@@@@" ; SLOWPOKE
	db "אוגלר@@@@@" ; KADABRA
	db "מחצץ@@@@@@" ; GRAVELER
	db "בת-מזל@@@@" ; CHANSEY
	db "גברנק@@@@@" ; MACHOKE
	db "מרחקיין@@@" ; MR.MIME
	db "הכמפמדג'ה@@" ; HITMONLEE
	db "הכמפארד@@@" ; HITMONCHAN
	db "נתף@@@@@@@" ; ARBOK
	db "טפרק@@@@@@" ; PARASECT
	db "תקשורווז@@" ; PSYDUCK
	db "ישנום@@@@@" ; DROWZEE
	db "גוילם@@@@@" ; GOLEM
	db "MISSINGNO." ; MISSINGNO.
	db "לברווז@@@@" ; MAGMAR
	db "MISSINGNO." ; MISSINGNO.
	db "חשמזום@@@@" ; ELECTABUZZ
	db "קוטבת@@@@@" ; MAGNETON
	db "משתעשן@@@@" ; KOFFING
	db "MISSINGNO." ; MISSINGNO.
	db "קופבני@@@@" ; MANKEY
	db "נבים@@@@@@" ; SEEL
	db "חפיד@@@@@@" ; DIGLETT
	db "פרסוס@@@@@" ; TAUROS
	db "MISSINGNO." ; MISSINGNO.
	db "MISSINGNO." ; MISSINGNO.
	db "MISSINGNO." ; MISSINGNO.
	db "לוסביר@@@@" ; FARFETCH'D
	db "רעתוש@@@@@" ; VENONAT
	db "לטאביר@@@@" ; DRAGONITE
	db "MISSINGNO." ; MISSINGNO.
	db "MISSINGNO." ; MISSINGNO.
	db "MISSINGNO." ; MISSINGNO.
	db "שנישלו@@@@" ; DODUO
	db "ראשנע@@@@@" ; POLIWAG
	db "בישה@@@@@@" ; JYNX
	db "מותלאתה@@@" ; MOLTRES
	db "קיפאוואחד@" ; ARTICUNO
	db "חשמתנן@@@@" ; ZAPDOS
	db "שינוץ@@@@@" ; DITTO
	db "מיצי@@@@@@" ; MEOWTH
	db "שרטני@@@@@" ; KRABBY
	db "MISSINGNO." ; MISSINGNO.
	db "MISSINGNO." ; MISSINGNO.
	db "MISSINGNO." ; MISSINGNO.
	db "ששועל@@@@@" ; VULPIX
	db "תשעלים@@@@" ; NINETALES
	db "צויצוץ@@@@" ; PIKACHU
	db "עכברעם@@@@" ; RAICHU
	db "MISSINGNO." ; MISSINGNO.
	db "MISSINGNO." ; MISSINGNO.
	db "לטנה@@@@@@" ; DRATINI
	db "לטאוויר@@@" ; DRAGONAIR
	db "פרסדה@@@@@" ; KABUTO
	db "פרצודה@@@@" ; KABUTOPS
	db "ימסוס@@@@@" ; HORSEA
	db "אץ-ים@@@@@" ; SEADRA
	db "MISSINGNO." ; MISSINGNO.
	db "MISSINGNO." ; MISSINGNO.
	db "חותחול@@@@" ; SANDSHREW
	db "חולדף@@@@@" ; SANDSLASH
	db "סילוני@@@@" ; OMANYTE
	db "סילוכב@@@@" ; OMASTAR
	db "ניענפוח@@@" ; JIGGLYPUFF
	db "כישקשוח@@@" ; WIGGLYTUFF
	db "פאתו@@@@@@" ; EEVEE
	db "נורידן@@@@" ; FLAREON
	db "זעידן@@@@@" ; JOLTEON
	db "אדידן@@@@@" ; VAPOREON
	db "גברכה@@@@@" ; MACHOP
	db "אצלף@@@@@@" ; ZUBAT
	db "שחן@@@@@@@" ; EKANS
	db "טפל@@@@@@@" ; PARAS
	db "ראשבוב@@@@" ; POLIWHIRL
	db "ראשזעם@@@@" ; POLIWRATH
	db "תולחט@@@@@" ; WEEDLE
	db "גלגולם@@@@" ; KAKUNA
	db "מקדבור@@@@" ; BEEDRILL
	db "MISSINGNO." ; MISSINGNO.
	db "שלושלו@@@@" ; DODRIO
	db "קופזועם@@@" ; PRIMEAPE
	db "חפליה@@@@@" ; DUGTRIO
	db "רעלש@@@@@@" ; VENOMOTH
	db "טלחש@@@@@@" ; DEWGONG
	db "MISSINGNO." ; MISSINGNO.
	db "MISSINGNO." ; MISSINGNO.
	db "זחי@@@@@@@" ; CATERPIE
	db "שינורמיל@@" ; METAPOD
	db "פרפרץ@@@@@" ; BUTTERFREE
	db "גברלוף@@@@" ; MACHAMP
	db "MISSINGNO." ; MISSINGNO.
	db "ברווזהב@@@" ; GOLDUCK
	db "מושין@@@@@" ; HYPNO
	db "בלעלף@@@@@" ; GOLBAT
	db "תשני@@@@@@" ; MEWTWO
	db "נוחרפל@@@@" ; SNORLAX
	db "קסמנון@@@@" ; MAGIKARP
	db "MISSINGNO." ; MISSINGNO.
	db "MISSINGNO." ; MISSINGNO.
	db "מרפש@@@@@@" ; MUK
	db "MISSINGNO." ; MISSINGNO.
	db "כנרטן@@@@@" ; KINGLER
	db "מבוצדף@@@@" ; CLOYSTER
	db "MISSINGNO." ; MISSINGNO.
	db "מוקשמל@@@@" ; ELECTRODE
	db "חמשל@@@@@@" ; CLEFABLE
	db "משתעשניים@" ; WEEZING
	db "קיצי@@@@@@" ; PERSIAN
	db "קרקש@@@@@@" ; MAROWAK
	db "MISSINGNO." ; MISSINGNO.
	db "רוצד@@@@@@" ; HAUNTER
	db "זריפון@@@@" ; ABRA
	db "ליאורד@@@@" ; ALAKAZAM
	db "סילונה@@@@" ; PIDGEOTTO
	db "יונה-עשרה@" ; PIDGEOT
	db "כוכשיט@@@@" ; STARMIE
	db "מוזרע@@@@@" ; BULBASAUR
	db "דשונה@@@@@" ; VENUSAUR
	db "מרושוש@@@@" ; TENTACRUEL
	db "MISSINGNO." ; MISSINGNO.
	db "זהלכה@@@@@" ; GOLDEEN
	db "ימלך@@@@@@" ; SEAKING
	db "MISSINGNO." ; MISSINGNO.
	db "MISSINGNO." ; MISSINGNO.
	db "MISSINGNO." ; MISSINGNO.
	db "MISSINGNO." ; MISSINGNO.
	db "סיחום@@@@@" ; PONYTA
	db "סוסורף@@@@" ; RAPIDASH
	db "עכברסס@@@@" ; RATTATA
	db "הדברוש@@@@" ; RATICATE
	db "עקצחלן@@@@" ; NIDORINO
	db "עקצחלנית@@" ; NIDORINA
	db "בחורקע@@@@" ; GEODUDE
	db "מצולען@@@@" ; PORYGON
	db "אווירונעף@" ; AERODACTYL
	db "MISSINGNO." ; MISSINGNO.
	db "שואבן@@@@@" ; MAGNEMITE
	db "MISSINGNO." ; MISSINGNO.
	db "MISSINGNO." ; MISSINGNO.
	db "גחומט@@@@@" ; CHARMANDER
	db "שפריצב@@@@" ; SQUIRTLE
	db "חזיזיקית@@" ; CHARMELEON
	db "קרבצב@@@@@" ; WARTORTLE
	db "לטאש@@@@@@" ; CHARIZARD
	db "MISSINGNO." ; MISSINGNO.
	db "MISSINGNO." ; MISSINGNO.
	db "MISSINGNO." ; MISSINGNO.
	db "MISSINGNO." ; MISSINGNO.
	db "צנוזר@@@@@" ; ODDISH
	db "פריכאון@@@" ; GLOOM
	db "עשנבל@@@@@" ; VILEPLUME
	db "פעמוניצן@@" ; BELLSPROUT
	db "דמעמון@@@@" ; WEEPINBELL
	db "תהילעמון@@" ; VICTREEBEL
